DROP TABLE IF EXISTS role;

CREATE TABLE role (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(250) NOT NULL
);

	
DROP TABLE IF EXISTS user;

CREATE TABLE user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(250) NOT NULL,
	email VARCHAR(250) NOT NULL,
	password VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS user_role;

CREATE TABLE user_role (
	FOREIGN KEY(id_user) REFERENCES user,
	FOREIGN KEY(id_role) REFERENCES role
);



